"""Compare a generated definition against the one a book's own authors wrote.

The reference makes exactly one question answerable — does the generated definition
assert something the author's contradicts — and that question is put to a model whose
verdict is auditable, because both texts are printed beside it.

The other two soundness failure modes ADR-0005 names, fragmentary and vacuous, are
properties of the generated text alone. A model grading those is a model grading a
model with nothing that could falsify it, so they are approximated by rules and
reported as flags: places to look, never judgements, and never summed into a score.

Design and pre-registered readings: `docs/research/2026-08-17-definition-comparison.md`.
"""

from __future__ import annotations

import re
from typing import Literal

from pydantic import BaseModel, Field

from glossary_gen.llm import extract_json
from glossary_gen.models import slugify

# Short enough that no real definition reaches it: the shortest in the first full book
# run was 61 characters, and the excerpt floor already refuses to ground anything on less.
_MIN_DEFINITION_CHARS = 25
_CLAUSE_END = re.compile(r"[,;:.]")
_LEADING_ARTICLE = re.compile(r"^\s*(?:a|an|the)\s+", re.I)

JUDGE_PROMPT = """You are comparing two definitions of the same term from a statistics textbook.

Term: {term}

Definition A, written by the textbook's authors:
{author}

Definition B, generated by a tool:
{generated}

Answer one question: does B assert something that A contradicts?

A difference in wording, length, emphasis, or examples is NOT a contradiction. B saying
more than A is not a contradiction. Only answer "contradicts" when the two cannot both
be true of the same concept.

Reply with JSON only:
{{"verdict": "contradicts" | "consistent" | "unclear", "reason": "one sentence naming
the specific claim that conflicts, or why the two agree"}}"""


class Verdict(BaseModel):
    """One judged pair. `reason` is required so a verdict can always be checked."""

    verdict: Literal["contradicts", "consistent", "unclear"]
    reason: str = Field(min_length=1)


def structural_flags(*, term: str, definition: str, reference: str) -> tuple[str, ...]:
    """Cheap observations about a generated definition. Sorted, because they land in a
    CSV column that gets diffed and set order would make identical results look changed.
    """
    flags = []
    text = definition.strip()

    if len(text) < _MIN_DEFINITION_CHARS or not text.endswith((".", "!", "?")):
        flags.append("no-sentence")

    # Opening with the term is ordinary prose ("A random sample is one in which..."). Only
    # a first clause that IS the term says the definition added nothing to it. The leading
    # article comes off first, or "A random sample, which..." reads as a real definition.
    first_clause = _LEADING_ARTICLE.sub("", _CLAUSE_END.split(text, maxsplit=1)[0])
    if slugify(first_clause) == slugify(term):
        flags.append("restates-term")

    if reference and len(text) * 2 < len(reference.strip()):
        flags.append("much-shorter")

    return tuple(sorted(flags))


def judge_prompt(*, term: str, author: str, generated: str) -> str:
    return JUDGE_PROMPT.format(term=term, author=author, generated=generated)


def parse_verdict(raw: str) -> Verdict:
    """Validate rather than coerce: a judge answering "mostly consistent" must fail
    loudly, or an unparsed reply becomes a clean result nobody questions.
    """
    return Verdict.model_validate(extract_json(raw))
